# Generated by Django 3.2.8 on 2021-12-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('airing', models.BooleanField(default=False)),
                ('synopsis', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=50)),
                ('episodes', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rated', models.CharField(max_length=50)),
            ],
        ),
    ]
