# Generated by Django 3.2.8 on 2021-12-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('replies', '0001_initial'),
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comments'),
        ),
        migrations.AddField(
            model_name='anime',
            name='replies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replies.replies'),
        ),
    ]
