# Generated by Django 3.2.8 on 2021-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='animes',
        ),
        migrations.AddField(
            model_name='comments',
            name='anime_id',
            field=models.IntegerField(default=0),
        ),
    ]
